---
inventory:
  all_children:
    targets:
      hosts:
        "{{ target_hostname }}":
          ansible_host: "{{ target_hostname }}"
          ansible_user: "{{ username }}"
          ansible_ssh_private_key_file: ./ssh_key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=new'

files:
  - variable: "{{ ssh_key_variable }}"
    target: ./ssh_key
    mode: '0600'

extra_vars:
  target_hostname:
    type: string
  username:
    type: string
    default: root
  ssh_key_variable:
    type: string
  sysctl_params:
    type: object

dependencies:
  python:
    - jmespath

---
- name: Apply network optimization parameters
  hosts: targets
  become: yes
  tasks:
    - name: Apply sysctl parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop: "{{ sysctl_params | dict2items }}"
      register: sysctl_result

    - name: Gather results
      set_fact:
        applied_params: "{{ sysctl_result.results | selectattr('changed', 'equalto', true) | map(attribute='item') | list }}"

    - name: Return success result
      delegate_to: localhost
      copy:
        content: "{{ { 'success': true, 'hostname': target_hostname, 'applied_count': applied_params | length, 'applied_params': applied_params } | to_json }}"
        dest: result.json